### PR TITLE
Feature/upload size

### PR DESCRIPTION
**Pull request by mallorydxw**

### CODE REVIEW

**Comment by mallorydxw** [comment]
Resolves: #1

**Comment by RobjS** [comment]
@mallorydxw Other than a rebase, what do we need to do to get this out of draft and ready to merge?

**Comment by mallorydxw** [comment]
I rebased and tested. It seems to be working. Not sure why I left it as a draft.

A ~400MB file to test it with: https://en.wikipedia.org/wiki/File:Cheetahs_on_the_Edge_(Director%27s_Cut).ogv

**Review by RobjS — APPROVED** [review]
👍

**Pull request merged**
