### PR TITLE
Ask before overwriting existing wpc files

### PR DESCRIPTION
**Pull request by RobjS**
This isn't as DRY as I would like, but I hit a couple of issues I couldn't work out a better way around:

a) We've already populated the stdin by the time we call `creating_noexec`, so `read`ing the stdin doesn't work. There's probably a way around that by assigning the file input to a variable, but...
b) We're also doing some find/replace work that varies on a file-by-file basis, and depending on whether you've set `--multisite`. We don't want to do the find and replace if the user hasn't chosen to overwrite the file, so checking if it's ok to overwrite within `creating_noexec` wouldn't work anyway.

If you've got any suggestions on a better approach, happy to hear them. My bash knowledge is pretty limited.

### CODE REVIEW

**Comment by mallorydxw** [comment]
> If you've got any suggestions on a better approach, happy to hear them. My bash knowledge is pretty limited.

My rule of thumb is:

- write it in shell
- if it starts getting a bit too complex then rewrite it in a better language

**Comment by mallorydxw** [comment]
I pushed a couple of extra commits to this branch. I replaced `[[` and `=~` because dash doesn't like them. And I replaced `perl` with `sed`.

I did some basic cross-platform testing too (both interactively and non-interactively):

```
core@workshop /workbench/src/github.com/dxw/wpc [ask-user-before-overwrite-file]
% docker run -ti --rm -v`pwd`:/app:ro debian /app/bin/wpc_init --multisite meow
-> Creating directory bin
-> Creating directory setup
-> Creating directory setup/content
-> Creating docker-compose.yml
-> Creating bin/wp
-> Creating bin/console
-> Creating bin/setup
-> Creating setup/external.sh
-> Creating setup/internal.sh
-> Creating directory config
-> Creating config/server.php
✔

core@workshop /workbench/src/github.com/dxw/wpc [ask-user-before-overwrite-file]
% docker run -ti --rm -v`pwd`:/app:ro alpine /app/bin/wpc_init --multisite meow                  
-> Creating directory bin
-> Creating directory setup
-> Creating directory setup/content
-> Creating docker-compose.yml
-> Creating bin/wp
-> Creating bin/console
-> Creating bin/setup
-> Creating setup/external.sh
-> Creating setup/internal.sh
-> Creating directory config
-> Creating config/server.php
✔ 2

core@workshop /workbench/src/github.com/dxw/wpc [ask-user-before-overwrite-file]
% docker run -ti --rm -v`pwd`:/app:ro fedora /app/bin/wpc_init --multisite meow
-> Creating directory bin
-> Creating directory setup
-> Creating directory setup/content
-> Creating docker-compose.yml
-> Creating bin/wp
-> Creating bin/console
-> Creating bin/setup
-> Creating setup/external.sh
-> Creating setup/internal.sh
-> Creating directory config
-> Creating config/server.php
✔ 2

core@workshop /workbench/src/github.com/dxw/wpc [ask-user-before-overwrite-file]
% docker run -ti --rm -v`pwd`:/app --workdir=/app/test/ alpine /app/bin/wpc_init --multisite meow
-> Creating directory bin
-> Creating directory setup
-> Creating directory setup/content
The file docker-compose.yml already exists. Do you want to overwrite it? (y/n)
y
-> Creating docker-compose.yml
The file bin/wp already exists. Do you want to overwrite it? (y/n)
y
-> Creating bin/wp
The file bin/console already exists. Do you want to overwrite it? (y/n)
n
The file bin/setup already exists. Do you want to overwrite it? (y/n)
n
The file setup/external.sh already exists. Do you want to overwrite it? (y/n)
y
-> Creating setup/external.sh
The file setup/internal.sh already exists. Do you want to overwrite it? (y/n)
n
✔ 8
```

(Debian uses `dash`, Fedora uses `bash`, and Alpine uses `busybox`. The Fedora and Alpine images don't include `perl`.)

**Review by mallorydxw — APPROVED** [review]
All appears to be working now.

Feel free to merge once you've looked at/tested my changes.

**Comment by RobjS** [comment]
Hmm, my OS doesn't seem to like that last commit (`d58b96a`). In a WP app repo:

```
$ ls
README.md    bin          config       setup        whippet.json whippet.lock wp-content
$ wpc_init a-wpc-project-name
...
$ ls
README.md            config               docker-compose.yml-e whippet.json         wp-content
bin                  docker-compose.yml   setup                whippet.lock
```

I also get an extra `internal.sh-e`, as well as `internal.sh`.

**Comment by mallorydxw** [comment]
@RobjS 

Using `sed -i '' -e 's/a/b/' xyz` works on Darwin. But GNU sed complains:

```
% sed -i '' -e 's/a/b/' xyz
sed: can't read : No such file or directory
```

And `sed -e 's/a/b/' xyz -i` works with GNU sed but Darwin's sed complains:

```
$ sed -e 's/a/b/' xyz -i
sed: -i: No such file or directory
```

Pushed a fix that uses .bak files (and deletes them).

**Pull request merged**
