### PR TITLE
Feature/shellcheck

### PR DESCRIPTION
**Pull request by mallorydxw**

### CODE REVIEW

**Review by erbridge — APPROVED** [review]
LGTM

**Comment by RobjS** [comment]
I have one reservation here, which is that linters that can't autofix the errors they highlight (which, as I understand it, shellcheck generally can't: https://www.vidarholen.net/contents/blog/?p=793) can result in devs having to manually parse the linter's output and make the fixes, which can be a time-consuming and painful process.

Practically speaking, the changes we make after this PR to any specific shell script in this repo will probably be relatively minor, so that may not be much of an issue. But I think it's worth raising, just in case.

**Comment by erbridge** [comment]
I think encouraging people to be linting as they develop is a practice we should get into. It's something we do for non-PHP things already.

**Comment by mallorydxw** [comment]
I agree that's autofixing is an important feature of a linter. But do you know of any that do autofixing?

I did a quick Google and found [shfmt](https://github.com/mvdan/sh#shfmt) which autofixes, but it looks like it only handles indenting.

**Pull request merged**
