### PR TITLE
Implement Scripts To Rule Them All pattern

### PR DESCRIPTION
**Pull request by mallorydxw**
https://github.com/dxw/tech-team-rfcs/blob/master/rfc-023-use-scripts-to-rule-them-all.md

https://github.com/github/scripts-to-rule-them-all

- [x] Add placeholder scripts
- [x] Whippet should be properly versioned
- [x] Add a `composer.json` file that lists `whippet` as a dev-dependency
- ~Run `composer update` after running `wpc`~ (Not needed as running `script/bootstrap`/`composer install` will create the `composer.lock` file)
- [x] `script/bootstrap` should check for dependencies (docker, docker-compose, php, composer), run `composer install` to install `whippet`, then run `vendor/bin/whippet deps install`
- [x] `script/console` should call `bin/console`
- [x] `script/server` should call `docker-compose down --remove-orphans && docker-compose up`
- [x] `script/setup` should call `bin/setup`
- [x] `script/update` should call `script/bootstrap`
- [x] Deprecate the old bin/ commands by adding a warning to each of them (`wp` can stay)
- [x] Append `/vendor/` to the `.gitignore` file (create the file if it doesn't exist yet)

### CODE REVIEW

**Comment by RobjS** [comment]
@mallorydxw I'm wondering if we could manage without running `composer update` as part of `wpc`. If we don't, the default behaviour would be that `wpc` generates a `composer.json` (but no `composer.lock`), and the `composer install` command that is run when running `script/bootstrap` will generate a `composer.lock` based on the latest versions of those dependencies. What do you think?

**Comment by mallorydxw** [comment]
@RobjS I agree, happy to leave a `composer.json` file without a `composer.lock` file. I didn't realise `composer install` would create a lockfile.

**Comment by jacksonj04** [comment]
I agree with not putting a `composer update` in any of these scripts, but I think we _should_ be committing the `composer.lock` since that ensures any installed dependencies are pegged to the right versions. If there's no `composer.lock` then what you'll get is a mix of dependency versions in different places.

Updating `composer.lock` should be an explicit, conscious action taken by a developer running `composer update`.

**Comment by mallorydxw** [comment]
@RobjS I've finished the last item on the list. It should add `/vendor/` to the `.gitignore` file only if `/vendor/` is not found on any other line. And it should create the file if it doesn't exist yet.

Edit: I also rewrote one of your commits to use version `1.0` of whippet instead of `dev-master`.

**Pull request merged**
